// Regenerates the two files that tie the app's country list to the boundaries the map draws:
//
//   src/data/boundary-codes.ts - Natural Earth's alpha-3 keys, translated to ISO 3166-1 alpha-2
//   src/data/countries.ts      - the same list, with `bounds` taken from those boundaries
//
// Run it with `pnpm run generate:countries` after bumping `visionscarto-world-atlas`. The country
// list is the input, not the output: a country the atlas cannot draw fails the run rather than
// quietly disappearing, so dropping one is always a deliberate edit to src/data/countries.ts.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import isoCountries from "i18n-iso-countries";
import type { Topology } from "topojson-specification";

import { boundsOf, toBoundaries } from "../src/data/boundaries.ts";
import type { Bounds } from "../src/data/boundaries.ts";
import { countries } from "../src/data/countries.ts";
import type { Country } from "../src/models/country.ts";

const resolve = (path: string): string => fileURLToPath(new globalThis.URL(path, import.meta.url));

const ATLAS_PATH = resolve("../node_modules/visionscarto-world-atlas/world/50m.json");
const CODES_PATH = resolve("../src/data/boundary-codes.ts");
const COUNTRIES_PATH = resolve("../src/data/countries.ts");

// Natural Earth carries Kosovo as the user-assigned `XKX`, which is not in ISO 3166-1 and so is
// absent from the lookup table. Every other country resolves from its alpha-3 code.
const ALPHA3_OVERRIDES: Readonly<Record<string, string>> = { XKX: "XK" };

type BoundedCountry = Country & { readonly bounds: Bounds };

// oxlint-disable-next-line typescript/no-unsafe-type-assertion -- A file installed from npm, not untrusted input.
const readAtlas = (): Topology => JSON.parse(readFileSync(ATLAS_PATH, "utf8")) as Topology;

const alpha3sOf = (topology: Topology): readonly string[] => {
	const object = topology.objects["countries"];
	if (object?.type !== "GeometryCollection") {
		throw new Error("The world atlas has no `countries` collection.");
	}
	return object.geometries.flatMap((geometry) => {
		const properties: Readonly<Record<string, unknown>> = geometry.properties ?? {};
		const alpha3 = properties["a3"];
		return typeof alpha3 === "string" ? [alpha3] : [];
	});
};

// Only the countries the app lists, so a code the app does not track can never reach the map.
const toCodes = (topology: Topology): Readonly<Record<string, string>> => {
	const tracked = new Set(countries.map(({ iso3166 }) => iso3166));
	const codes: Record<string, string> = {};
	for (const alpha3 of alpha3sOf(topology)) {
		const iso3166 = isoCountries.alpha3ToAlpha2(alpha3) ?? ALPHA3_OVERRIDES[alpha3];
		if (iso3166 !== undefined && tracked.has(iso3166)) {
			codes[alpha3] = iso3166;
		}
	}
	return codes;
};

const withBounds = (
	topology: Topology,
	codes: Readonly<Record<string, string>>,
): readonly BoundedCountry[] => {
	const boundaries = new Map(
		toBoundaries(topology, codes).features.map((boundary) => [
			boundary.properties.iso_3166_1,
			boundary,
		]),
	);

	const missing = countries.filter(({ iso3166 }) => !boundaries.has(iso3166));
	if (missing.length > 0) {
		throw new Error(
			`Natural Earth has no geometry for ${missing.length} of the listed countries: ` +
				`${missing.map(({ iso3166, name }) => `${name} (${iso3166})`).join(", ")}. Either the ` +
				`atlas changed shape, or these need removing from src/data/countries.ts.`,
		);
	}

	return countries.map(({ iso3166, name, region }) => {
		const boundary = boundaries.get(iso3166);
		if (boundary === undefined) {
			throw new Error(`No boundary for ${name}.`);
		}
		return { bounds: boundsOf(boundary), iso3166, name, region };
	});
};

const serializeCodes = (codes: Readonly<Record<string, string>>): string =>
	[
		"// Generated by `pnpm run generate:countries`. Do not edit by hand.",
		"// Maps Natural Earth's alpha-3 country keys to the ISO 3166-1 alpha-2 codes the app uses.",
		"export const boundaryCodes: Readonly<Record<string, string>> = {",
		...Object.keys(codes)
			.toSorted()
			.map((alpha3) => `\t${alpha3}: ${JSON.stringify(codes[alpha3])},`),
		"};",
		"",
	].join("\n");

const serializeCountries = (values: readonly BoundedCountry[]): string =>
	[
		"// oxlint-disable max-lines -- A static dataset of every country, not code to be split up.",
		"// Bounds are generated by `pnpm run generate:countries`; edit that script, not these numbers.",
		'import type { Country } from "../models/country";',
		"",
		"export const countries: readonly Country[] = [",
		...values.map(({ bounds, iso3166, name, region }) =>
			[
				"\t{",
				`\t\tbounds: [${bounds.join(", ")}],`,
				`\t\tiso3166: ${JSON.stringify(iso3166)},`,
				`\t\tname: ${JSON.stringify(name)},`,
				`\t\tregion: ${JSON.stringify(region)},`,
				"\t},",
			].join("\n"),
		),
		"];",
		"",
	].join("\n");

const atlas = readAtlas();
const codes = toCodes(atlas);
const bounded = withBounds(atlas, codes);

writeFileSync(CODES_PATH, serializeCodes(codes));
writeFileSync(COUNTRIES_PATH, serializeCountries(bounded));

console.warn(`Wrote ${Object.keys(codes).length} boundary codes and ${bounded.length} countries.`);
