on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  commit-message:
    name: semantic-pull-request
    if: contains(fromJson('["pull_request", "pull_request_target"]'), github.event_name)
    runs-on: ubuntu-22.04
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run stylelint
      - run: pnpm run format
      - run: pnpm run build
      - run: pnpm run test
      - uses: test-summary/action@v2
        with:
          paths: 'reports/*.xml'
  deploy:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build --deploy-url=/been/ --base-href=/been/
        env:
          API_KEY_MAPBOX: ${{ secrets.API_KEY_MAPBOX }}
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/browser
          force_orphan: true
