on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  commit-message:
    name: semantic-pull-request
    if: contains(fromJson('["pull_request", "pull_request_target"]'), github.event_name)
    runs-on: ubuntu-22.04
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm exec playwright install chromium
      - run: pnpm run lint
      - run: pnpm run build
        env:
          VITE_API_KEY_MAPBOX: ${{ secrets.API_KEY_MAPBOX }}
      - run: pnpm run test
        env:
          VITE_API_KEY_MAPBOX: ${{ secrets.API_KEY_MAPBOX }}
      - uses: test-summary/action@v2
        if: always()
        with:
          paths: 'reports/*.xml'
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
        env:
          VITE_API_KEY_MAPBOX: ${{ secrets.API_KEY_MAPBOX }}
      - uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 08bcfcb3f50021eafc9bd1bfb1f06ad0
          projectName: been
          directory: ./dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
